// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYEZE6BWX17f7bvg_aa9YWiavi3l48bg',
    appId: '1:1725150801:web:09466dff4ac64204826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    authDomain: 'project-b2728.firebaseapp.com',
    storageBucket: 'project-b2728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchsQYqLx3d22dZ2yGQzAz3Sl6y2C4y74',
    appId: '1:1725150801:android:33b7b3ebca57ce4b826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    storageBucket: 'project-b2728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEUXkPGycQZA5mBoDqo_dwAqkteYakWc',
    appId: '1:1725150801:ios:49bde366ff9cfa5f826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    storageBucket: 'project-b2728.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjEUXkPGycQZA5mBoDqo_dwAqkteYakWc',
    appId: '1:1725150801:ios:39afa60eb64b2599826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    storageBucket: 'project-b2728.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
