// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYEZE6BWX17f7bvg_aa9YWiavi3l48bg',
    appId: '1:1725150801:web:09466dff4ac64204826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    authDomain: 'project-b2728.firebaseapp.com',
    databaseURL: 'https://project-b2728-default-rtdb.firebaseio.com',
    storageBucket: 'project-b2728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchsQYqLx3d22dZ2yGQzAz3Sl6y2C4y74',
    appId: '1:1725150801:android:2a0fce7b82ca5b60826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    databaseURL: 'https://project-b2728-default-rtdb.firebaseio.com',
    storageBucket: 'project-b2728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEUXkPGycQZA5mBoDqo_dwAqkteYakWc',
    appId: '1:1725150801:ios:76d97131d0dca84a826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    databaseURL: 'https://project-b2728-default-rtdb.firebaseio.com',
    storageBucket: 'project-b2728.appspot.com',
    androidClientId: '1725150801-s2rs63uaecdn11l9j2odh7buc61p7p47.apps.googleusercontent.com',
    iosClientId: '1725150801-ddii4omhs8sfnu5f25rutt01sdrdumje.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjEUXkPGycQZA5mBoDqo_dwAqkteYakWc',
    appId: '1:1725150801:ios:572ead10003c75c1826a70',
    messagingSenderId: '1725150801',
    projectId: 'project-b2728',
    databaseURL: 'https://project-b2728-default-rtdb.firebaseio.com',
    storageBucket: 'project-b2728.appspot.com',
    androidClientId: '1725150801-s2rs63uaecdn11l9j2odh7buc61p7p47.apps.googleusercontent.com',
    iosClientId: '1725150801-e1ug5c5eff1us5fe2d9rn0uk4m1kca0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDemo.RunnerTests',
  );
}
